f = open('aboutbook.txt', 'r')
line = f.readline()
print('A line from file is:', line)
f.seek(5)
line = f.readline()
print('The line from character 6 till end of line is:', line)
print('The pointer is at location', f.tell())
f.seek(11)
line = f.read(15)
print('The fifteen characters starting at location 12 are as:', line)
